[base]
; package = ocean
env_name = balatro
; policy_name = Policy
; rnn_name = Recurrent

[vec]
total_agents = 8192
; total_agents = 1024
; total_agents =  512
num_buffers = 4
num_threads = 12

[env]
;unsure if need to set num_agents
num_agents = 1
; reward_completed_blind = 1.0
reward_completed_blind = 0.5
reward_unused_hand = 0.15
reward_failure_penalty = -1.0
reward_illegal_action_penalty = -0.2
reward_deselect_penalty = -0.1

[train]
total_timesteps = 20_000_000
num_workers = 2
gamma = 0.95
learning_rate = 0.05
; batch_size = auto
minibatch_size = 8192
seed = 42
horizon = 64
; Uncomment for randomizing every training run
; seed = 0 


[sweep]
metric = perf

[sweep.train.total_timesteps]
distribution = uniform
min = 10_000_000
max = 200_000_000
scale = 0.5

[sweep.env.reward_completed_blind]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.reward_unused_hand]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.reward_failure_penalty]
distribution = uniform
min = 0.0
max = -1.0
scale = auto

[sweep.env.reward_illegal_action_penalty]
distribution = uniform
min = 0.0
max = -1.0
scale = auto

[sweep.env.reward_deselect_penalty]
distribution = uniform
min = 0.0
max = -1.0
scale = auto

